name: Exercise tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  test:
    name: Go ${{ matrix.ruby-version }} - ${{ matrix.os }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        ruby-version: [2.5]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-ruby@v1
        with:
          version: ${{ matrix.ruby-version }}

      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Bundle install
        run: |
          bundle config path vendor/bundle
          bundle install --quiet

      - name: Lint 
        run: rubocop -fs -D

      - name: Test exercises
        env:
          TESTARCH: ${{ test-arch }}
        run: rake test
