name: Exercise tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  test:
    name: Go ${{ matrix.julia-version }} - ${{ matrix.os }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.14.x, 1.15.x]
        os: [ubuntu-latest, windows-latest, macOS-latest]
        test-arch: [amd64, '386']
        race: ['', '-race']

        # Race detection is valuable for our problems that involve concurrency.
        # The race detector isn't supported on 386 though.
        exclude:
          - test-arch: '386'
            race: -race
          - test-arch: amd64
            race: ''

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-ruby@v1
        with:
          version: 2.5

      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Bundle install
        run: |
          bundle config path vendor/bundle
          bundle install --quiet

      - name: Lint 
        run: rubocop -fs -D

      - name: Test exercises
        env:
          TESTARCH: ${{ test-arch }}
        run: rake test
